# docker-compose build or up
version: '3'
services:
  koa:
    build:
      context: ./koa
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./koa/main.js:/app/main.js
  oak:
    build:
      context: ./oak
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./oak/mod.ts:/app/mod.ts    
  oakjs:
    build:
      context: ./oakjs
      dockerfile: Dockerfile
    ports:
      - "8002:8000"
    volumes:
      - ./oakjs/mod.js:/app/mod.js   
  deno:
    build:
      context: ./deno
      dockerfile: Dockerfile
    ports:
      - "8003:8000"
    volumes:
      - ./deno/mod.ts:/app/mod.ts     
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - "8004:8000"
    volumes:
      - ./node/main.js:/app/main.js               